// console.log("hello world from JS");
// console.log("hello Mayy");
let a = " Toi la String";
// console.log(a);
// console.log(4 + 5 + "a");
// console.log("a" + 5 + 4);
let text = "Tu hoc JS";
console.log(text.length);
console.log(text.replace("JS", "Code"));
console.log(text.toUpperCase());
console.log(a);
